In [ ]:
!pip install vanna

In [13]:
import pandas as pd
from sqlalchemy import create_engine
from vanna.remote import VannaDefault

In [14]:
vn = VannaDefault(model='chinook', api_key='55c52579f71345b2aa48d2b7c0acfba9')
#vn = VannaDefault(model='chinook', api_key=vanna.get_api_key('your@email.com'))

In [15]:
vn.connect_to_sqlite('https://vanna.ai/Chinook.sqlite')

In [ ]:
from IPython.display import Image
schema="https://m-soro.github.io/Business-Analytics/SQL-for-Data-Analysis/L4-Project-Query-Music-Store/Misc/001.png"
Image(schema)

In [2]:
engine=create_engine('sqlite:///Chinook.sqlite')
con= pd.read_sql_query("SELECT * FROM album", engine)    
print(con)

OperationalError: (sqlite3.OperationalError) no such table: album
[SQL: SELECT * FROM album]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [ ]:
engine

In [3]:
from sqlalchemy import create_engine
import pandas as pd
engine=create_engine('sqlite:///Chinook.sqlite')
con= pd.read_sql_query("SELECT * FROM Album", engine)    
print(con)

OperationalError: (sqlite3.OperationalError) no such table: Album
[SQL: SELECT * FROM Album]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [7]:
tables = pd.read_sql("""SELECT *
                        """, engine)

tables

OperationalError: (sqlite3.OperationalError) no tables specified
[SQL: SELECT *
                        ]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [4]:
engine

Engine(sqlite:///Chinook.sqlite)

In [8]:
tables = pd.read_sql(
"""
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' 
AND TABLE_SCHEMA='public'
""", 
engine)

tables

OperationalError: (sqlite3.OperationalError) no such table: INFORMATION_SCHEMA.TABLES
[SQL:
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
AND TABLE_SCHEMA='public'
]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [10]:
# Import necessary module
from sqlalchemy import create_engine

# Create engine: engine
engine = create_engine('https://github.com/lerocha/chinook-database/blob/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite') 

# Save the table names to a list: table_names
table_names = engine.table_names()

# Print the table names to the shell
print(table_names)

NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:https

In [12]:
from sqlalchemy import create_engine
import pandas as pd
engine= create_engine('sqlite:///Chinook.sqlite')
con= pd.read_sql_query("SELECT * FROM Album", engine)    
print(con)

OperationalError: (sqlite3.OperationalError) no such table: Album
[SQL: SELECT * FROM Album]
(Background on this error at: https://sqlalche.me/e/14/e3q8)